/*****************************************************************/
/* Author  : Ahmed                                               */
/* Layer   : MCAL                                                */
/* SWC     : USART                                               */
/* Version : 1.0                                                 */
/* Date    : 25 Dec 2023                                         */
/*****************************************************************/
#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define USART_U2X USART_U2X_DISABLE
/**Options
* USART_U2X_DISABLE
* USART_U2X_ENABLE
*/


#define USART_MULTI_PROCESSOR USART_MULTI_PROCESSOR_DISABLE
/**Options
* USART_MULTI_PROCESSOR_DISABLE
* USART_MULTI_PROCESSOR_ENABLE
*/


#define USART_RX_INTERRUPT USART_RX_INTERRUPT_ENABLE
/**Options
* USART_RX_INTERRUPT_DISABLE
* USART_RX_INTERRUPT_ENABLE
*/


#define USART_TX_INTERRUPT USART_TX_INTERRUPT_DISABLE
/**Options
* USART_TX_INTERRUPT_DISABLE
* USART_TX_INTERRUPT_ENABLE
*/


#define USART_DATA_EMPTY_INTERRUPT USART_DATA_EMPTY_INTERRUPT_DISABLE
/**Options
* USART_DATA_EMPTY_INTERRUPT_DISABLE
* USART_DATA_EMPTY_INTERRUPT_ENABLE
*/


#define USART_RECEIVER USART_RECEIVER_ENABLE
/**Options
* USART_RECEIVER_DISABLE
* USART_RECEIVER_ENABLE
*/


#define USART_TRANSMITTER USART_TRANSMITTER_DISABLE
/**Options
* USART_TRANSMITTER_DISABLE
* USART_TRANSMITTER_ENABLE
*/


#define USART_CHARACTER_SIZE USART_CHARACTER_SIZE_8BIT
/**Options
* USART_CHARACTER_SIZE_5BIT
* USART_CHARACTER_SIZE_6BIT
* USART_CHARACTER_SIZE_7BIT
* USART_CHARACTER_SIZE_8BIT
* USART_CHARACTER_SIZE_9BIT
*/


#define USART_MODE USART_MODE_ASYNCHRONOUS
/**Options
* USART_MODE_ASYNCHRONOUS
* USART_MODE_SYNCHRONOUS
*/


#define USART_PARITY USART_PARITY_DISABLED
/**Options
* USART_PARITY_DISABLE
* USART_PARITY_EVEN
* USART_PARITY_ODD
*/


#define USART_STOP_BIT USART_STOP_BIT_1BIT
/**Options
* USART_STOP_BIT_1BIT
* USART_STOP_BIT_2BIT
*/


#define USART_CLK_POLARITY USART_CLK_POLARITY_RISING_TRANSMIT
/**Options
* USART_CLK_POLARITY_RISING_TRANSMIT
* USART_CLK_POLARITY_FALLING_TRANSMIT
*/


#define USART_BAUD_RATE USART_BAUD_RATE_9600
/**Options
* USART_BAUD_RATE_2400
* USART_BAUD_RATE_4800
* USART_BAUD_RATE_9600
* USART_BAUD_RATE_14400
* USART_BAUD_RATE_19200
* USART_BAUD_RATE_28800
* USART_BAUD_RATE_38400
* USART_BAUD_RATE_57600
* USART_BAUD_RATE_76800
* USART_BAUD_RATE_115200
* USART_BAUD_RATE_230400
* USART_BAUD_RATE_250000
* USART_BAUD_RATE_500000
*/

#endif
