/*****************************************************************/
/* Author  : Ahmed                                               */
/* Layer   : MCAL                                                */
/* SWC     : TIMER1                                              */
/* Version : 1.0                                                 */
/* Date    : 13 Jan 2024                                         */
/*****************************************************************/
#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_



#define TIMER1_WG_MODE TIMER1_WG_MODE_PWM_FAST_ICR1
/* Options
* TIMER1_WG_MODE_NORMAL
* TIMER1_WG_MODE_PWM_PHASE_CORRECT_8BIT
* TIMER1_WG_MODE_PWM_PHASE_CORRECT_9BIT
* TIMER1_WG_MODE_PWM_PHASE_CORRECT_10BIT
* TIMER1_WG_MODE_CTC_OCR1A
* TIMER1_WG_MODE_PWM_FAST_8BIT
* TIMER1_WG_MODE_PWM_FAST_9BIT
* TIMER1_WG_MODE_PWM_FAST_10BIT
* TIMER1_WG_MODE_PWM_PHASE_FREQ_CORRECT_ICR1
* TIMER1_WG_MODE_PWM_PHASE_FREQ_CORRECT_OCR1A
* TIMER1_WG_MODE_PWM_PHASE_CORRECT_ICR1
* TIMER1_WG_MODE_PWM_PHASE_CORRECT_OCR1A
* TIMER1_WG_MODE_CTC_ICR1
* TIMER1_WG_MODE_PWM_FAST_ICR1
* TIMER1_WG_MODE_PWM_FAST_OCR1A
*/


#define TIMER1_CMP_NONPWM_OUTPUTA_MODE TIMER1_CMP_NONPWM_OUTPUTA_MODE_OFF
/* Options
* TIMER1_CMP_NONPWM_OUTPUTA_MODE_OFF
* TIMER1_CMP_NONPWM_OUTPUTA_MODE_TOGGLE
* TIMER1_CMP_NONPWM_OUTPUTA_MODE_CLEAR
* TIMER1_CMP_NONPWM_OUTPUTA_MODE_SET
*/


#define TIMER1_CMP_FASTPWM_OUTPUTA_MODE TIMER1_CMP_FASTPWM_OUTPUTA_MODE_CLEAR_CM_SET_TOP
/* Options
* TIMER1_CMP_FASTPWM_OUTPUTA_MODE_OFF
* ???????????????????????????
* TIMER1_CMP_FASTPWM_OUTPUTA_MODE_CLEAR_CM_SET_TOP
* TIMER1_CMP_FASTPWM_OUTPUTA_MODE_SET_CM_CLEAR_TOP
*/


#define TIMER1_CMP_PCPWM_OUTPUTA_MODE TIMER1_CMP_PCPWM_OUTPUTA_MODE_OFF
/* Options
* TIMER1_CMP_PCPWM_OUTPUTA_MODE_OFF
* ????????????????????????????????
* TIMER1_CMP_PCPWM_OUTPUTA_MODE_CLEAR_UP_SET_DOWN
* TIMER1_CMP_PCPWM_OUTPUTA_MODE_SET_UP_CLEAR_DOWN
*/

#define TIMER1_CMP_NONPWM_OUTPUTB_MODE TIMER1_CMP_NONPWM_OUTPUTB_MODE_OFF
/* Options
* TIMER1_CMP_NONPWM_OUTPUTB_MODE_OFF
* TIMER1_CMP_NONPWM_OUTPUTB_MODE_TOGGLE
* TIMER1_CMP_NONPWM_OUTPUTB_MODE_CLEAR
* TIMER1_CMP_NONPWM_OUTPUTB_MODE_SET
*/


#define TIMER1_CMP_FASTPWM_OUTPUTB_MODE TIMER1_CMP_FASTPWM_OUTPUTB_MODE_OFF
/* Options
* TIMER1_CMP_FASTPWM_OUTPUTB_MODE_OFF
* ???????????????????????????
* TIMER1_CMP_FASTPWM_OUTPUTB_MODE_CLEAR_CM_SET_TOP
* TIMER1_CMP_FASTPWM_OUTPUTB_MODE_SET_CM_CLEAR_TOP
*/


#define TIMER1_CMP_PCPWM_OUTPUTB_MODE TIMER1_CMP_PCPWM_OUTPUTB_MODE_OFF
/* Options
* TIMER1_CMP_PCPWM_OUTPUTB_MODE_OFF
* ????????????????????????????????
* TIMER1_CMP_PCPWM_OUTPUTB_MODE_CLEAR_UP_SET_DOWN
* TIMER1_CMP_PCPWM_OUTPUTB_MODE_SET_UP_CLEAR_DOWN
*/

#define TIMER1_INPUT_NOISE_CANCELER TIMER1_INPUT_NOISE_CANCELER_DISABLE
/* Options
* TIMER1_INPUT_NOISE_CANCELER_DISABLE
* TIMER1_INPUT_NOISE_CANCELER_ENABLE
*/

#define TIMER1_CLK_PRESCALER TIMER1_CLK_PRESCALER_8
/* Options
* TIMER1_CLK_PRESCALER_TIMER_OFF
* TIMER1_CLK_PRESCALER_1
* TIMER1_CLK_PRESCALER_8
* TIMER1_CLK_PRESCALER_64
* TIMER1_CLK_PRESCALER_256
* TIMER1_CLK_PRESCALER_1024
* TIMER1_CLK_PRESCALER_EXTERNAL_FALLING_EDGE
* TIMER1_CLK_PRESCALER_EXTERNAL_RISING_EDGE
*/


#define TIMER1_INTERRUPT_OVF_MODE TIMER1_INTERRUPT_OVF_MODE_DISABLE
/* Options
* TIMER1_INTERRUPT_OVF_MODE_DISABLE
* TIMER1_INTERRUPT_OVF_MODE_ENABLE
*/


#define TIMER1_INTERRUPT_CMA_MODE TIMER1_INTERRUPT_CMA_MODE_DISABLE
/* Options
* TIMER1_INTERRUPT_CMA_MODE_DISABLE
* TIMER1_INTERRUPT_CMA_MODE_ENABLE
*/

#define TIMER1_INTERRUPT_CMB_MODE TIMER1_INTERRUPT_CMB_MODE_DISABLE
/* Options
* TIMER1_INTERRUPT_CMB_MODE_DISABLE
* TIMER1_INTERRUPT_CMB_MODE_ENABLE
*/


#endif
